image: 
  name: sonarsource/sonar-scanner-cli:4.7.0  # Try a specific, stable version
  entrypoint: [""]

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SONAR_SCANNER_OPTS: "-Xmx512m"  # Provide explicit memory allocation

stages:
  - build-sonar

build-sonar:
  stage: build-sonar
  
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
  
  before_script:
    - echo "Testing connection to SonarQube server at ${SONAR_HOST_URL}"
    - curl -I ${SONAR_HOST_URL} || true  # Just see what happens, but continue anyway
    - echo "Scanner version:"
    - sonar-scanner --version
    
  script: 
    - sonar-scanner -X -Dsonar.projectKey="muhammedbarghou_Watchly_1956c35f-69da-4d35-a102-3f9e2d322b82" -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.login="${SONAR_TOKEN}"
  
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'